name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Rustc version
      run: rustc -Vv
    - name: Cargo version
      run: cargo -Vv
    - name: Run tests
      run: cargo test --verbose
  Clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Clippy
      run: rustup component add clippy
    - name: Rustc version
      run: rustc -Vv
    - name: Cargo version
      run: cargo -Vv
    - name: Check Clippy
      run: cargo clippy --all-targets
  Rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add rustfmt
      run: rustup component add rustfmt
    - name: Rustc version
      run: rustc -Vv
    - name: Cargo version
      run: cargo -Vv
    - name: Check formatting
      run: cargo fmt --all -- --check
